Repository FinnyJakey/Podo-Market, pull requests merged in 2023-11, with the labels that each got.

#6 빌드 검사 워크플로우 추가 ->dev
  .github/workflows/gradle.yml
Labels: chore

#13 Feature(ViewModel)#9: add ViewModel for Authentication and Board
  app/build.gradle
  app/src/main/java/com/example/podomarket/model/BoardModel.kt
  app/src/main/java/com/example/podomarket/viewmodel/AuthViewModel.kt
  app/src/main/java/com/example/podomarket/viewmodel/BoardViewModel.kt
Labels: enhancement

#14 Feature/#8 로그인, 계정생성 레이아웃 변경, 검증 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/podomarket/LoginActivity.kt
  app/src/main/java/com/example/podomarket/LoginUiState.kt
  app/src/main/java/com/example/podomarket/MainActivity.kt
  app/src/main/java/com/example/podomarket/SignUpActivity.kt
  app/src/main/java/com/example/podomarket/SignUpUiState.kt
  app/src/main/res/drawable/ic_calendar.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/strings.xml
Labels: UI, enhancement

#17 fix: 비번 검증 #16
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/podomarket/MainActivity.kt
  app/src/main/java/com/example/podomarket/login/LoginActivity.kt
  app/src/main/java/com/example/podomarket/login/LoginUiState.kt
  app/src/main/java/com/example/podomarket/signup/SignUpActivity.kt
  app/src/main/java/com/example/podomarket/signup/SignUpUiState.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_sign_up.xml
Labels: fix

#19 Feature/#18 레이아웃 수정
  .gitignore
  app/src/main/java/com/example/podomarket/MainActivity.kt
  app/src/main/java/com/example/podomarket/product/ProductListFragment.kt
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_like.xml
  app/src/main/res/drawable/ic_like_fill.xml
  app/src/main/res/drawable/ic_logout.xml
  app/src/main/res/drawable/product_like_checkbox.xml
  app/src/main/res/drawable/product_sold_check_active.xml
  app/src/main/res/drawable/product_sold_check_inactive.xml
  app/src/main/res/drawable/product_sold_checkbox.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_product_detail.xml
  app/src/main/res/layout/fragment_product_list.xml
Labels: UI, enhancement, refactor

#21 Feature(Chat): add chat model/viewmodel
  app/src/main/java/com/example/podomarket/TestActivity.kt
  app/src/main/java/com/example/podomarket/model/ChatModel.kt
  app/src/main/java/com/example/podomarket/viewmodel/ChatViewModel.kt
Labels: back, enhancement

#23 Feature/#22 로그인, 회원가입 레이아웃 수정
  app/src/main/java/com/example/podomarket/login/LoginActivity.kt
  app/src/main/java/com/example/podomarket/login/LoginErrorMessages.kt
  app/src/main/java/com/example/podomarket/login/LoginUiState.kt
  app/src/main/java/com/example/podomarket/signup/SignUpActivity.kt
  app/src/main/java/com/example/podomarket/signup/SignUpErrorMessages.kt
  app/src/main/java/com/example/podomarket/signup/SignUpUiState.kt
  app/src/main/res/drawable/grapes.png
  app/src/main/res/drawable/logo_text.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values/styles.xml
Labels: UI, refactor

#25 Feature/#20 판매 게시물 추가, 수정, 목록 레이아웃과 뷰모델 연결
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/podomarket/login/LoginUiState.kt
  app/src/main/java/com/example/podomarket/product/ProductAddFragment.kt
  app/src/main/java/com/example/podomarket/product/ProductAddUiState.kt
  app/src/main/java/com/example/podomarket/product/ProductDetailFragment.kt
  app/src/main/java/com/example/podomarket/product/ProductEditFragment.kt
  app/src/main/java/com/example/podomarket/product/ProductEditUiState.kt
  app/src/main/java/com/example/podomarket/product/ProductListFragment.kt
  app/src/main/java/com/example/podomarket/product/ProductRecyclerViewAdapter.kt
  app/src/main/java/com/example/podomarket/signup/SignUpActivity.kt
  app/src/main/java/com/example/podomarket/signup/SignUpUiState.kt
  app/src/main/java/com/example/podomarket/viewmodel/AuthViewModel.kt
  app/src/main/res/layout/fragment_product_add.xml
  app/src/main/res/layout/fragment_product_detail.xml
  app/src/main/res/layout/fragment_product_edit.xml
  app/src/main/res/layout/product_item.xml
Labels: back, enhancement

#34 Feature/#29 판매글 레이아웃 수정
  app/src/main/java/com/example/podomarket/common/CommonUtil.kt
  app/src/main/java/com/example/podomarket/product/ProductDetailFragment.kt
  app/src/main/java/com/example/podomarket/product/ProductRecyclerViewAdapter.kt
  app/src/main/res/layout/fragment_product_detail.xml
Labels: UI, fix, refactor

#36 enter누를시 로그인 가능, 게시물 목록 판매 필터링 추가
  app/src/main/java/com/example/podomarket/login/LoginActivity.kt
  app/src/main/java/com/example/podomarket/product/ProductListFragment.kt
  app/src/main/res/layout/fragment_product_list.xml
Labels: enhancement

#35 Refactor(Board): refactor BoardViewModel functions
  app/src/main/java/com/example/podomarket/product/ProductAddFragment.kt
  app/src/main/java/com/example/podomarket/product/ProductEditFragment.kt
  app/src/main/java/com/example/podomarket/viewmodel/BoardViewModel.kt
Labels: refactor

#37 Feature/#31 뒤로가기 시 경고 메세지 출력, 기타 코드 수정
  app/src/main/java/com/example/podomarket/product/ProductAddFragment.kt
  app/src/main/java/com/example/podomarket/product/ProductEditFragment.kt
  app/src/main/res/layout/fragment_product_detail.xml
  app/src/main/res/layout/fragment_product_list.xml
Labels: UI, fix, refactor

#38 Feature&Refactor(#28): Board / Chat ViewModel Updates
  app/src/main/java/com/example/podomarket/TestActivity.kt
  app/src/main/java/com/example/podomarket/model/ChatModel.kt
  app/src/main/java/com/example/podomarket/product/ProductAddFragment.kt
  app/src/main/java/com/example/podomarket/viewmodel/AuthViewModel.kt
  app/src/main/java/com/example/podomarket/viewmodel/BoardViewModel.kt
  app/src/main/java/com/example/podomarket/viewmodel/ChatViewModel.kt
Labels: enhancement, refactor

#39 Feature/#27 판매글 이미지 레이아웃 추가
  app/src/main/java/com/example/podomarket/common/CommonUtil.kt
  app/src/main/java/com/example/podomarket/product/ProductAddFragment.kt
  app/src/main/java/com/example/podomarket/product/ProductDetailFragment.kt
  app/src/main/java/com/example/podomarket/product/ProductDisplayPageAdapter.kt
  app/src/main/java/com/example/podomarket/product/ProductEditFragment.kt
  app/src/main/java/com/example/podomarket/product/ProductImagePagerAdapter.kt
  app/src/main/java/com/example/podomarket/product/ThumbnailRecyclerViewAdapter.kt
  app/src/main/java/com/example/podomarket/viewmodel/BoardViewModel.kt
  app/src/main/res/drawable/ic_circle_gray.xml
  app/src/main/res/drawable/ic_circle_white.xml
  app/src/main/res/drawable/ic_close_black.xml
  app/src/main/res/drawable/image_delete_button_background.xml
  app/src/main/res/layout/fragment_product_add.xml
  app/src/main/res/layout/fragment_product_detail.xml
  app/src/main/res/layout/fragment_product_edit.xml
  app/src/main/res/layout/product_image_item.xml
  app/src/main/res/layout/product_image_page_item.xml
  app/src/main/res/layout/product_thumbnail_item.xml
Labels: UI, enhancement, refactor

#43 Feature/#42 ChatViewModel, ChatRoomModel id추가
  app/src/main/java/com/example/podomarket/model/ChatModel.kt
  app/src/main/java/com/example/podomarket/viewmodel/ChatViewModel.kt
Labels: fix

#49 Feature/#48 판매글 상세 페이지 수정
  app/src/main/res/layout/fragment_product_detail.xml
Labels: UI, refactor

#44 Feature/#40 채팅방 레이아웃 db 데이터 적용
  app/src/main/java/com/example/podomarket/chat/ChatRoomBubbleRecyclerViewAdapter.kt
  app/src/main/java/com/example/podomarket/chat/ChatRoomFragment.kt
  app/src/main/java/com/example/podomarket/product/ProductDetailFragment.kt
  app/src/main/res/layout/chat_room_me_item.xml
  app/src/main/res/layout/chat_room_you_item.xml
  app/src/main/res/layout/fragment_chat_room.xml
Labels: UI, refactor

#47 Feature/#46 디테일 화면 -> 채팅방 화면으로 데이터 전송 후 프래그먼트 실행
  app/src/main/java/com/example/podomarket/product/ProductDetailFragment.kt
Labels: UI, refactor

#41 Feature/#32 내 채팅 목록 보기 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/podomarket/chat/ChatListFragment.kt
  app/src/main/java/com/example/podomarket/chat/ChatListRecyclerViewAdapter.kt
  app/src/main/java/com/example/podomarket/chat/ChatRoomFragment.kt
  app/src/main/res/layout/chat_item.xml
Labels: back, enhancement

#54 Feature(Chat): update in real-time for ChatListFragment & ChatRoomFragment
  app/src/main/java/com/example/podomarket/chat/ChatListFragment.kt
  app/src/main/java/com/example/podomarket/chat/ChatRoomFragment.kt
Labels: enhancement

#55 Feature/#53 사용자에 따른 '채팅하기'버튼 존재여부 다르게 구현
  app/src/main/java/com/example/podomarket/product/ProductDetailFragment.kt
  app/src/main/res/layout/fragment_product_detail.xml
Labels: enhancement

#56 feat: 채팅방 레이아웃 수정
  app/src/main/java/com/example/podomarket/chat/ChatRoomBubbleRecyclerViewAdapter.kt
  app/src/main/java/com/example/podomarket/chat/ChatRoomFragment.kt
  app/src/main/java/com/example/podomarket/common/CommonUtil.kt
Labels: UI, refactor

#57 Feature/#52 레이아웃 수정
  app/src/main/java/com/example/podomarket/chat/ChatRoomBubbleRecyclerViewAdapter.kt
  app/src/main/java/com/example/podomarket/chat/ChatRoomFragment.kt
  app/src/main/res/layout/chat_item.xml
  app/src/main/res/layout/chat_room_me_item.xml
  app/src/main/res/layout/chat_room_you_item.xml
  app/src/main/res/layout/fragment_chat_room.xml
  app/src/main/res/layout/fragment_product_detail.xml
  app/src/main/res/layout/product_image_item.xml
  app/src/main/res/layout/product_item.xml
Labels: UI, refactor
